### ISSUE TITLE
Folder template returns name as "folders/<folder_id>" but project template wants only the "id" as part of parent property

### ISSUE THREAD

**Issue by kansberry** [GoogleCloudPlatform/cloud-foundation-toolkit#628] opened 2020-04-03 15:43 UTC
Using CFT, I am attempting to create my folders in my first deployment and my projects in a second deployment. However, the output of the folder creation API is the "name", which contains "folders/<folder_id>", and the project parent property requires simply the "id". How can I turn the value in "$(out.project.deployment.folder-resource-name.name)" into a value that parent id will take? This is the error I get:

    Manifest expansion encountered the following errors: Invalid properties for 'project.py':
    [] is not of type 'integer', 'string' at ['parent', 'id']

Based on the error, it appears variable $(out.project.deployment.folder-resource-name.name) is null, so this would be related to CFT?

**Comment by frots** [comment] 2020-05-22 15:50
see https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/357

**Comment by morgante** [comment] 2020-05-26 20:13
Closing as a dupe of #357.

**Closed by morgante** 2020-05-26 20:13 UTC
Labels: DM

**Comment by ocsig** [comment] 2020-07-24 22:33
This is a known limitation of Deployment Manager. It is not possible to do string manipulation on referenced values, such as the folder ID coming back from the GCP API.
Unfortunately it means you can not create a folder and a project within the same deployment.
Arguably folders should be managed separately from projects anyway, so my advice is to create folders in one deployment while each project in its own deployment where the folder ID is an input parameter to the deployment. This requires the input to be queried and fed into the second deployment by your automation system/script.
