### ISSUE TITLE
[KCC] Issue with owned-project IAMPolicyMember

### ISSUE THREAD

**Issue by trodge** [GoogleCloudPlatform/cloud-foundation-toolkit#654] opened 2020-04-22 16:25 UTC
The IAMPolicyMember in owned-project fails to apply with the following error message:
```
    Message:               error setting policy member: error applying changes: Batch "iam-project-
projects/tjr-owned-project-13398 modifyIamPolicy" for request "Create IAM Members roles/owner
 user:notaraptor@gmail.com for \"project \\\"projects/tjr-owned-project-13398\\\"\"" 
returned error: Error applying IAM policy for project "projects/tjr-owned-project-13398": Error 
setting IAM policy for project "projects/tjr-owned-project-13398": googleapi: Error 400: Request 
contains an invalid argument., badRequest
```

**Comment by caieo** [comment] 2020-04-24 00:09
Hey @trodge , KCC bugs/issues should be filed directly to the [ConfigConnector repository](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues), otherwise we won't have a direct way to receive them.

**Comment by AlexBulankou** [comment] 2020-04-26 22:50
@BrianPi , can you please confirm if this is an issue with the solution or with the Config Connector, and in case it is the latter, open a bug in [Config Connector repo](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues).
@caieo, since this is likely an issue with the solution, we would like to start by opening the bugs in this repo.

**Comment by AlexBulankou** [comment] 2020-04-28 17:13
Discussed at standup, @trodge  can still repro, @BrianPi  verifying.

**Comment by BrianPi** [comment] 2020-04-28 18:04
Able to reproduce after setting `iam-member` to a user. Looks related to https://github.com/terraform-providers/terraform-provider-google/issues/4276.

**Comment by BrianPi** [comment] 2020-04-29 16:13
https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/162

**Comment by BrianPi** [comment] 2020-05-07 21:15
Basic issue appears to be a new Google Cloud Platform bug with cross-org permissions. Closing because it should not affect most users, and is beyond the scope of KCC solutions.

**Closed by BrianPi** 2020-05-07 21:15 UTC
Labels: KCC
